### ISSUE TITLE
MPOS needed changes 

### ISSUE THREAD

**Issue by mmitech** [ocminer/ethcore-pool-mpos#1]
Can you please add a folder and include the changes that needs to be changed in MPSO for it to get working ?

**Comment by ocminer** [comment]
Sorry those are not public yet.

**Comment by zimbo123** [comment]
Hello,
the changes are not public, can you give some help with the global config? In the global config must be the algo inserted, but the ethash is not listed. Can i use one of the examples (scrypt, sha256d, x11 ,...)?
What data of the ethereum-proxy should i use for the wallet-config?
No username and Password? And rewrite some classes?
With Port should i use? The port from the porxy-settings in the ethereum-proxy, or the port from the upstream?

Thanks a lot.

Best regards

Zimbo
