### ISSUE TITLE
Ethereum RPC credentials

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [ocminer/ethcore-pool-mpos#3]
Hello, I found not how to configure the "user" and "password" in the RPC configuration wallet in MPOS

``` bash
/**
 * Local wallet RPC
 *  RPC configuration for your daemon/wallet
 *   https://github.com/MPOS/php-mpos/wiki/Config-Setup#wiki-local-wallet-rpc
 **/
$config['wallet']['type'] = 'http';
$config['wallet']['host'] = '10.10.11.46:8545';
$config['wallet']['username'] = '';
$config['wallet']['password'] = '';
```

Knowing that I activated RPC in ETH console

``` bash
admin.startRPC("10.10.11.46", 8545, "*", "web3,db,net,eth")
```

Do you have a suggestion to solve this?

**Comment by ocminer** [comment]
You'll have FAR (!) more todo than this :) The RPC from ETH is totally different from bitcoin (and its clones) - you have to rewrite quite some classes of MPOS to get it running with ETH. bitcoinwrapper.class.php for example and much more..
